module.exports = {
  up: (queryInterface) =>
    queryInterface.bulkInsert(
      "Products",
      [
        {
          name: "Jacket",
          price: 2000,
          bonus: 2000,
          images: [
            "https://res.cloudinary.com/dqk2wjyyz/image/upload/v1683798080/TrojansEcommerce/tplbrfvoyqyumfkb85ir.jpg",
            "https://res.cloudinary.com/dqk2wjyyz/image/upload/v1683798081/TrojansEcommerce/ssf9c8op4b3udh1irpfs.jpg",
            "https://res.cloudinary.com/dqk2wjyyz/image/upload/v1683798081/TrojansEcommerce/gwpu0qrm30ku8f8rf0lk.jpg",
            "https://res.cloudinary.com/dqk2wjyyz/image/upload/v1683798082/TrojansEcommerce/hxnajulhcabokrqpfdff.jpg",
          ],
          sellerId: 2,
          expiryDate: new Date("2035/01/01"),
          quantity: 20,
          categoryId: 1,
          available: true,
          expired: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Nike Airforce",
          price: 2500,
          bonus: 0,
          images: [
            "https://res.cloudinary.com/dqk2wjyyz/image/upload/v1683794641/TrojansEcommerce/siwj4flswisnv79ie9m8.png",
            "https://res.cloudinary.com/dqk2wjyyz/image/upload/v1683794641/TrojansEcommerce/d66fbuqborgosnjgfgfn.png",
            "https://res.cloudinary.com/dqk2wjyyz/image/upload/v1683794642/TrojansEcommerce/zgk42daai79d91cayfm1.png",
            "https://res.cloudinary.com/dqk2wjyyz/image/upload/v1683794642/TrojansEcommerce/ywnafhcu7bvem2jxourm.png",
          ],
          sellerId: 7,
          expiryDate: new Date("2027/01/01"),
          quantity: 20,
          categoryId: 1,
          available: true,
          expired: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Black Sweater",
          price: 3000,
          bonus: 0,
          images: [
            "https://res.cloudinary.com/dqk2wjyyz/image/upload/v1683798517/TrojansEcommerce/z8kpl0gqmu29pxxmhgmg.jpg",
            "https://res.cloudinary.com/dqk2wjyyz/image/upload/v1683798517/TrojansEcommerce/x6fiofbruaxndxftfwqb.jpg",
            "https://res.cloudinary.com/dqk2wjyyz/image/upload/v1683798518/TrojansEcommerce/rfnwma3gzspdafhgqn1n.jpg",
            "https://res.cloudinary.com/dqk2wjyyz/image/upload/v1683798518/TrojansEcommerce/glkuakjplcavdjws76ar.jpg",
          ],
          sellerId: 2,
          expiryDate: new Date("2060/01/01"),
          quantity: 20,
          categoryId: 2,
          available: true,
          expired: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "gray sweatpants",
          price: 15000,
          bonus: 0,
          images: [
            "https://res.cloudinary.com/dmyztchh9/image/upload/v1683815876/gray_sweatpant1_xvrhpv.webp",
            "https://res.cloudinary.com/dmyztchh9/image/upload/v1683815876/graysweatpant2_rshsdw.avif",
            "https://res.cloudinary.com/dmyztchh9/image/upload/v1683815876/gray_sweatpant_3_wofggo.jpg",
            "https://res.cloudinary.com/dmyztchh9/image/upload/v1683815876/gray_sweatpant_4_j2oa9n.jpg",
          ],
          sellerId: 6,
          expiryDate: new Date("2024/01/01"),
          quantity: 20,
          categoryId: 2,
          available: true,
          expired: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Iphone 14 pro",
          price: 3000,
          bonus: 0,
          images: [
            "https://res.cloudinary.com/dmyztchh9/image/upload/v1683815875/iphone_14_1_o60aaj.webp",
            "https://res.cloudinary.com/dmyztchh9/image/upload/v1683815875/iphone_14_2_fgljdv.jpg",
            "https://res.cloudinary.com/dmyztchh9/image/upload/v1683815874/iphone_14_4_hnwgzo.jpg",
            "https://res.cloudinary.com/dmyztchh9/image/upload/v1683815877/iphone_14_3_mokmuq.jpg"
          ],
          sellerId: 2,
          expiryDate: new Date("2050/01/01"),
          quantity: 20,
          categoryId: 4,
          available: true,
          expired: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "MacBook Pro",
          price: 50000,
          bonus: 0,
          images: [
            "https://res.cloudinary.com/dmyztchh9/image/upload/v1683815874/macBook_1_wqrcfg.jpg",
            "https://res.cloudinary.com/dmyztchh9/image/upload/v1683815874/macbook_2_gzjf0t.jpg",
            "https://res.cloudinary.com/dmyztchh9/image/upload/v1683815873/macbook_4_afelxw.jpg",
            "https://res.cloudinary.com/dmyztchh9/image/upload/v1683815874/macbook_3_djozgo.webp"
          ],
          sellerId: 2,
          expiryDate: new Date("2024/01/01"),
          quantity: 20,
          categoryId: 5,
          available: true,
          expired: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "ADIDAS",
          price: 2000,
          bonus: 2000,
          images: [
            "https://res.cloudinary.com/dqk2wjyyz/image/upload/v1683798917/TrojansEcommerce/camx7dnzniqf3b7blunl.jpg",
            "https://res.cloudinary.com/dqk2wjyyz/image/upload/v1683798918/TrojansEcommerce/y5gwlv6gzkcj4cc0a4xc.jpg",
            "https://res.cloudinary.com/dqk2wjyyz/image/upload/v1683798918/TrojansEcommerce/pqxkqoe7sk4mxxiiakri.jpg",
            "https://res.cloudinary.com/dqk2wjyyz/image/upload/v1683798918/TrojansEcommerce/fjxotj8ho1ufnnthpxgg.jpg",
          ],
          sellerId: 2,
          expiryDate: new Date(),
          quantity: 20,
          categoryId: 1,
          available: true,
          expired: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Iphone 12 mini",
          price: 1099,
          bonus: 10,
          images: [
            "https://res.cloudinary.com/dmyztchh9/image/upload/v1683816554/iphone_12_2_hjfszk.webp",
            "https://res.cloudinary.com/dmyztchh9/image/upload/v1683816612/iphone_12_mini_rhjgdo.jpg",
            "https://res.cloudinary.com/dmyztchh9/image/upload/v1683816553/iphone_12_4_lilpls.webp",
            "https://res.cloudinary.com/dmyztchh9/image/upload/v1683816553/iphone_12_3_p16exv.webp"
          ],
          sellerId: 2,
          expiryDate: new Date(),
          quantity: 20,
          categoryId: 4,
          available: true,
          expired: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "HP envy",
          price: 4000,
          bonus: 0,
          images: [
            "https://res.cloudinary.com/dmyztchh9/image/upload/v1683816553/hp_envy_1_l1atp8.jpg",
            "https://res.cloudinary.com/dmyztchh9/image/upload/v1683816553/hp_envy_2_c4lo2w.webp",
            "https://res.cloudinary.com/dmyztchh9/image/upload/v1683816553/hp_envy_3_kd696m.webp",
            "https://res.cloudinary.com/dmyztchh9/image/upload/v1683816553/hp_envy_3_kd696m.webp"
          ],
          sellerId: 2,
          expiryDate: new Date(),
          quantity: 20,
          categoryId: 5,
          available: true,
          expired: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Samsung Galaxy",
          price: 5000,
          bonus: 0,
          images: [
          "https://res.cloudinary.com/dmyztchh9/image/upload/v1683817189/Samsung_galaxy_1_cirqjq.jpg",
          "https://res.cloudinary.com/dmyztchh9/image/upload/v1683817189/samsung_3_vh2yqp.jpg",
          "https://res.cloudinary.com/dmyztchh9/image/upload/v1683817189/samsung_2_d9hqph.webp",
          "https://res.cloudinary.com/dmyztchh9/image/upload/v1683817189/samsung_4_zomhpc.webp"
          ],
          sellerId: 2,
          expiryDate: new Date(),
          quantity: 20,
          categoryId: 4,
          available: true,
          expired: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    ),

  down: (queryInterface) => queryInterface.bulkDelete("Products", null, {}),
};
